AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  PSU resources
# Params passed from the Makefile
Parameters:
  EnableMutualTLS:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  TruststoreVersion:
    Type: String
    Default: none

  LogLevel:
    Type: String
    Default: INFO

  LogRetentionInDays:
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1096
      - 1827
      - 2192
      - 2557
      - 2922
      - 3288
      - 3653

  EnableSplunk:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  EnableDynamoDBAutoScaling:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

  VersionNumber:
    Type: String
    Default: "xxx"

  CommitId:
    Type: String
    Default: "xxx"

  DeployCheckPrescriptionStatusUpdate:
    Type: String

  Environment:
    Type: String

  EnableAlerts:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

  DynamoDBUtilizationPercentageThreshold:
    Type: Number
    Description: When the database usage crosses this percentage of provisioned capacity, trigger an alarm
    Default: 90

  StateMachineLogLevel:
    Type: String

  EnableBackup:
    Type: String
    Default: "False"
    AllowedValues:
      - "True"
      - "False"

  EnableNotificationsInternal:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  EnableNotificationsExternal:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  EnabledSiteODSCodesValue:
    Type: String
    Default: " "

  EnabledSystemsValue:
    Type: String
    Default: " "

  BlockedSiteODSCodesValue:
    Type: String
    Default: " "

  NotifyRoutingPlanIDValue:
    Type: String
    Default: " "

  NotifyAPIBaseURLValue:
    Type: String
    Default: " "

  RequireApplicationName:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  TestPresciptionsParamValue1:
    Type: String

  TestPresciptionsParamValue2:
    Type: String

  TestPresciptionsParamValue3:
    Type: String

  TestPresciptionsParamValue4:
    Type: String

  ForwardCsocLogs:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
Resources:
  Secrets:
    Type: AWS::Serverless::Application
    Properties:
      Location: secrets/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName

  Parameters:
    Type: AWS::Serverless::Application
    Properties:
      Location: parameters/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        EnableNotificationsInternalValue: !Ref EnableNotificationsInternal
        EnableNotificationsExternalValue: !Ref EnableNotificationsExternal
        EnabledSiteODSCodesValue: !Ref EnabledSiteODSCodesValue
        EnabledSystemsValue: !Ref EnabledSystemsValue
        BlockedSiteODSCodesValue: !Ref BlockedSiteODSCodesValue
        NotifyRoutingPlanIDValue: !Ref NotifyRoutingPlanIDValue
        NotifyAPIBaseURLValue: !Ref NotifyAPIBaseURLValue
        TestPresciptionsParamValue1: !Ref TestPresciptionsParamValue1
        TestPresciptionsParamValue2: !Ref TestPresciptionsParamValue2
        TestPresciptionsParamValue3: !Ref TestPresciptionsParamValue3
        TestPresciptionsParamValue4: !Ref TestPresciptionsParamValue4

  Tables:
    Type: AWS::Serverless::Application
    Properties:
      Location: tables/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        EnableDynamoDBAutoScaling: !Ref EnableDynamoDBAutoScaling
        EnableBackup: !Ref EnableBackup

  Messaging:
    Type: AWS::Serverless::Application
    Properties:
      Location: messaging/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName

  Apis:
    Type: AWS::Serverless::Application
    Properties:
      Location: apis/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        EnableMutualTLS: !Ref EnableMutualTLS
        TruststoreVersion: !Ref TruststoreVersion
        UpdatePrescriptionStatusStateMachineName: !GetAtt StateMachines.Outputs.UpdatePrescriptionStatusStateMachineName
        UpdatePrescriptionStatusStateMachineArn: !GetAtt StateMachines.Outputs.UpdatePrescriptionStatusStateMachineArn
        Format1UpdatePrescriptionsStatusStateMachineName: !GetAtt StateMachines.Outputs.Format1UpdatePrescriptionsStatusStateMachineName
        Format1UpdatePrescriptionsStatusStateMachineArn: !GetAtt StateMachines.Outputs.Format1UpdatePrescriptionsStatusStateMachineArn
        StatusFunctionName: !GetAtt Functions.Outputs.StatusFunctionName
        StatusFunctionArn: !GetAtt Functions.Outputs.StatusFunctionArn
        CapabilityStatementFunctionName: !GetAtt Functions.Outputs.CapabilityStatementFunctionName
        CapabilityStatementFunctionArn: !GetAtt Functions.Outputs.CapabilityStatementFunctionArn
        CheckPrescriptionStatusUpdatesFunctionName: !GetAtt Functions.Outputs.CheckPrescriptionStatusUpdatesFunctionName
        CheckPrescriptionStatusUpdatesFunctionArn: !GetAtt Functions.Outputs.CheckPrescriptionStatusUpdatesFunctionArn
        NHSNotifyUpdateCallbackFunctionName: !GetAtt Functions.Outputs.NHSNotifyUpdateCallbackFunctionName
        NHSNotifyUpdateCallbackFunctionArn: !GetAtt Functions.Outputs.NHSNotifyUpdateCallbackFunctionArn
        LogRetentionInDays: !Ref LogRetentionInDays
        EnableSplunk: !Ref EnableSplunk
        DeployCheckPrescriptionStatusUpdate: !Ref DeployCheckPrescriptionStatusUpdate
        ForwardCsocLogs: !Ref ForwardCsocLogs

  Functions:
    Type: AWS::Serverless::Application
    Properties:
      Location: functions/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        PrescriptionStatusUpdatesTableName: !GetAtt Tables.Outputs.PrescriptionStatusUpdatesTableName
        PrescriptionNotificationStatesTableName: !GetAtt Tables.Outputs.PrescriptionNotificationStatesTableName
        NHSNotifyPrescriptionsSQSQueueUrl: !GetAtt Messaging.Outputs.NHSNotifyPrescriptionsSQSQueueUrl
        SQSSaltSecret: !GetAtt Secrets.Outputs.SQSSaltSecret
        EnabledSiteODSCodesParam: !GetAtt Parameters.Outputs.EnabledSiteODSCodesParameterName
        EnabledSystemsParam: !GetAtt Parameters.Outputs.EnabledSystemsParameterName
        BlockedSiteODSCodesParam: !GetAtt Parameters.Outputs.BlockedSiteODSCodesParameterName
        NotifyRoutingPlanIDParam: !GetAtt Parameters.Outputs.NotifyRoutingPlanIDParameterName
        NotifyAPIBaseURLParam: !GetAtt Parameters.Outputs.NotifyAPIBaseURLParameterName
        EnableNotificationsExternalParam: !GetAtt Parameters.Outputs.EnableNotificationsExternalName
        EnableNotificationsInternalParam: !GetAtt Parameters.Outputs.EnableNotificationsInternalName
        LogLevel: !Ref LogLevel
        LogRetentionInDays: !Ref LogRetentionInDays
        EnableSplunk: !Ref EnableSplunk
        VersionNumber: !Ref VersionNumber
        CommitId: !Ref CommitId
        DeployCheckPrescriptionStatusUpdate: !Ref DeployCheckPrescriptionStatusUpdate
        Environment: !Ref Environment
        EnableBackup: !Ref EnableBackup
        RequireApplicationName: !Ref RequireApplicationName
        TestPrescriptionsParamName1: !GetAtt Parameters.Outputs.TestPrescriptionsParameterName1
        TestPrescriptionsParamName2: !GetAtt Parameters.Outputs.TestPrescriptionsParameterName2
        TestPrescriptionsParamName3: !GetAtt Parameters.Outputs.TestPrescriptionsParameterName3
        TestPrescriptionsParamName4: !GetAtt Parameters.Outputs.TestPrescriptionsParameterName4

  StateMachines:
    Type: AWS::Serverless::Application
    Properties:
      Location: state_machines/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        UpdatePrescriptionStatusFunctionName: !GetAtt Functions.Outputs.UpdatePrescriptionStatusFunctionName
        UpdatePrescriptionStatusFunctionArn: !GetAtt Functions.Outputs.UpdatePrescriptionStatusFunctionArn
        ConvertRequestToFhirFormatFunctionName: !GetAtt Functions.Outputs.ConvertRequestToFhirFormatFunctionName
        ConvertRequestToFhirFormatFunctionArn: !GetAtt Functions.Outputs.ConvertRequestToFhirFormatFunctionArn
        LogRetentionInDays: !Ref LogRetentionInDays
        EnableSplunk: !Ref EnableSplunk
        StateMachineLogLevel: !Ref StateMachineLogLevel

  Alarms:
    Type: AWS::Serverless::Application
    Properties:
      Location: alarms/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        GetStatusUpdatesFunctionName: !GetAtt Functions.Outputs.GetStatusUpdatesFunctionName
        UpdatePrescriptionStatusFunctionName: !GetAtt Functions.Outputs.UpdatePrescriptionStatusFunctionName
        PrescriptionStatusUpdatesTableName: !GetAtt Tables.Outputs.PrescriptionStatusUpdatesTableName
        ConvertRequestToFhirFormatFunctionName: !GetAtt Functions.Outputs.ConvertRequestToFhirFormatFunctionName
        NotifyProcessorFunctionName: !GetAtt Functions.Outputs.NotifyProcessorFunctionName
        DynamoDBUtilizationPercentageThreshold: !Ref DynamoDBUtilizationPercentageThreshold
        EnableAlerts: !Ref EnableAlerts
