AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  SSM Parameter Store entries. Values may differ between prod and non-prod environments

Parameters:
  StackName:
    Type: String

  EnableNotificationsInternalValue:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  EnableNotificationsExternalValue:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  EnabledSiteODSCodesValue:
    Type: String
    Default: " "

  EnabledSystemsValue:
    Type: String
    Default: " "

  BlockedSiteODSCodesValue:
    Type: String
    Default: " "

  NotifyRoutingPlanIDValue:
    Type: String
    Default: " "

  NotifyAPIBaseURLValue:
    Type: String
    Default: " "
  
  TestPresciptionsParamValue1:
    Type: String

  TestPresciptionsParamValue2:
    Type: String

  TestPresciptionsParamValue3:
    Type: String

  TestPresciptionsParamValue4:
    Type: String

Resources:
  EnabledSiteODSCodesParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-PSUNotifyEnabledSiteODSCodes
      Description: "List of site ODS codes for which notifications are enabled"
      Type: String
      Value: !Ref EnabledSiteODSCodesValue

  EnabledSystemsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-PSUNotifyEnabledSystems
      Description: "List of application names for which notifications are enabled"
      Type: String
      Value: !Ref EnabledSystemsValue

  BlockedSiteODSCodesParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-PSUNotifyBlockedSiteODSCodes
      Description: "List of site ODS codes for which notifications are blocked"
      Type: String
      Value: !Ref BlockedSiteODSCodesValue

  NotifyRoutingPlanIDParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-PSUNotifyRoutingPlanID
      Description: "Notify Routing Plan ID"
      Type: String
      Value: !Ref NotifyRoutingPlanIDValue

  NotifyAPIBaseURLParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-PSUNotifyApiBaseUrl
      Description: "Notify API Base URL"
      Type: String
      Value: !Ref NotifyAPIBaseURLValue

  EnableNotificationsExternal:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-EnableNotificationsExternal
      Description: "Toggle on or off if we make real requests to the NHS notify service"
      Type: String
      Value: !Ref EnableNotificationsExternalValue

  EnableNotificationsInternal:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-EnableNotificationsInternal
      Description: "Toggle the notifications integration entirely"
      Type: String
      Value: !Ref EnableNotificationsInternalValue

  TestPrescriptionsParameter1:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-TEST_PRESCRIPTIONS_1
      Description: "Toggle the notifications integration entirely"
      Type: String
      Value: !Ref TestPresciptionsParamValue1

  TestPrescriptionsParameter2:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-TEST_PRESCRIPTIONS_2
      Description: "Toggle the notifications integration entirely"
      Type: String
      Value: !Ref TestPresciptionsParamValue2

  TestPrescriptionsParameter3:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-TEST_PRESCRIPTIONS_3
      Description: "Toggle the notifications integration entirely"
      Type: String
      Value: !Ref TestPresciptionsParamValue3

  TestPrescriptionsParameter4:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-TEST_PRESCRIPTIONS_4
      Description: "Toggle the notifications integration entirely"
      Type: String
      Value: !Ref TestPresciptionsParamValue4

  GetNotificationsParameterPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Allows reading SSM parameters"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
            Resource:
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${StackName}-PSUNotifyEnabledSiteODSCodes
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${StackName}-PSUNotifyEnabledSystems
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${StackName}-PSUNotifyBlockedSiteODSCodes
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${StackName}-PSUNotifyRoutingPlanID
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${StackName}-PSUNotifyApiBaseUrl
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${StackName}-EnableNotificationsExternal
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${StackName}-EnableNotificationsInternal
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${StackName}-TestPrescriptionsParameter1
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${StackName}-TestPrescriptionsParameter2
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${StackName}-TestPrescriptionsParameter3
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${StackName}-TestPrescriptionsParameter4


Outputs:
  EnabledSiteODSCodesParameterName:
    Description: "Name of the SSM parameter holding enabled site ODS codes"
    Value: !Ref EnabledSiteODSCodesParameter
    Export:
      Name: !Sub ${StackName}-PSUNotifyEnabledSiteODSCodesParam

  EnabledSystemsParameterName:
    Description: "Name of the SSM parameter holding enabled system names"
    Value: !Ref EnabledSystemsParameter
    Export:
      Name: !Sub ${StackName}-PSUNotifyEnabledSystemsParam

  BlockedSiteODSCodesParameterName:
    Description: "Name of the SSM parameter holding blocked site ODS codes"
    Value: !Ref BlockedSiteODSCodesParameter
    Export:
      Name: !Sub ${StackName}-PSUNotifyBlockedSiteODSCodesParam

  NotifyRoutingPlanIDParameterName:
    Description: "Name of the SSM parameter holding the Notify Routing Plan ID"
    Value: !Ref NotifyRoutingPlanIDParameter
    Export:
      Name: !Sub ${StackName}-PSUNotifyRoutingPlanIDParam

  NotifyAPIBaseURLParameterName:
    Description: "Name of the SSM parameter holding the Notify API Base URL"
    Value: !Ref NotifyAPIBaseURLParameter
    Export:
      Name: !Sub ${StackName}-PSUNotifyApiBaseUrlParam

  EnableNotificationsExternalName:
    Description: "Name of the SSM parameter holding the Notify API Base URL"
    Value: !Ref EnableNotificationsExternal
    Export:
      Name: !Sub ${StackName}-EnableNotificationsExternalName

  EnableNotificationsInternalName:
    Description: "Name of the SSM parameter holding the Notify API Base URL"
    Value: !Ref EnableNotificationsInternal
    Export:
      Name: !Sub ${StackName}-EnableNotificationsInternalName

  GetNotificationsParameterPolicy:
    Description: Access to the parameters used by the notifications integration
    Value: !Ref GetNotificationsParameterPolicy
    Export:
      Name: !Sub ${StackName}-GetNotificationsParameterPolicy

  TestPrescriptionsParameterName1:
    Description: "Name of the SSM parameter holding test prescriptions 1"
    Value: !Ref TestPrescriptionsParameter1
    Export:
      Name: !Sub ${StackName}-TestPrescriptionsParameterName1

  TestPrescriptionsParameterName2:
    Description: "Name of the SSM parameter holding test prescriptions 2"
    Value: !Ref TestPrescriptionsParameter2
    Export:
      Name: !Sub ${StackName}-TestPrescriptionsParameterName2

  TestPrescriptionsParameterName3:
    Description: "Name of the SSM parameter holding test prescriptions 3"
    Value: !Ref TestPrescriptionsParameter3
    Export:
      Name: !Sub ${StackName}-TestPrescriptionsParameterName3

  TestPrescriptionsParameterName4:
    Description: "Name of the SSM parameter holding test prescriptions 4"
    Value: !Ref TestPrescriptionsParameter4
    Export:
      Name: !Sub ${StackName}-TestPrescriptionsParameterName4
